development:
  host: localhost
  database: lovetube_development

test:
  host: localhost
  database: lovetube_test

# set these environment variables on your prod server
production:
  host: localhost
  database: lovetube 
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
